// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HelloSourceGenerator
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Program : TemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\n\r\nnamespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            this.Write("\r\n{\r\n    partial class Program\r\n    {\r\n        public static void SayHello()\r\n   " +
                    "     {\r\n            Console.WriteLine(\"Hello, T4 Template with Source Generator!" +
                    "\");\r\n");

foreach(var file in Files)
{

            this.Write("            Console.WriteLine(\" - ");
            this.Write(this.ToStringHelper.ToStringWithCulture(file.Replace("\\", "\\\\")));
            this.Write("\");\r\n");

}

            this.Write("        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
}
